---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install de
    package:
      name:
        - sway
        - waybar
        - alacritty
        - grim
        - wofi
  - name: set config
    copy:
      src: dotfiles/
      dest: /home/wyatt/.config
  - name: install dev packages
    package:
      name:
        - rust
  - name: install amp text editor
    command: cargo install amp
  
